services:
  api:
    build: 
      context: ./backend 
    ports:
      - 8000:8000
    depends_on:
      - mysql

    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos


  ui:
    build:
      context: ./frontend
    ports: 
      - 5173:5173
    depends_on:
      - api


  mysql:
    ports:
      - "3306:3306"
    expose:
      - "3306"
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10


volumes:
  todo-mysql-data:

