name: Continuos Deployment

on:
  workflow_call

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
  deploy-dev:
    needs: ["checkout"]
    name: deploy dev
    uses: ./.github/workflows/push&apply.yaml
    with:
      environment: "dev"
