name: CI/CD

on:
  push:
    branch: [main]


jobs:
  test-ui:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 21.x

    - name: Install npm modules 
      working-directory: ./frontend
      run: npm ci
    - name: Run unit test
      working-directory: ./frontend
      run: npm test

  integration:
    needs: ["test-ui"]
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Start containers
      run: docker compose up -d --build

    - name: Run migrations on database
      run: sleep 15 && docker compose run api ./todoapp migrations

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 21.x
    - name: Setup integration tests
      working-directory: ./api-integration-tests
      run: | 
        npm install
        npx playwright install
      #- name: Run Tests
        #working-directory: ./api-integration-tests
        #  run: npx playwright test
      
    - name: Stop containers
      if: always()
      run: docker compose down
  deployment:
    needs: ["integration"]
    uses: ./.github/workflows/continuos-deployment.yml
    secrets:
      aws_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
      aws_account_id: ${{secrets.AWS_ACCOUNT_ID}}
