name: "Deploy to AWS"

on:
  push:
    branches:
      - main


jobs:
  # build the image
  # send the image up to the ecr 

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Push FE Image to ECR
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

      run: |
        aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.us-east-2.amazonaws.com
        docker build --compress -t ${{vars.ECR_FRONT_REPO_APP}}:$GITHUB_SHA frontend
        docker push ${{vars.ECR_FRONT_REPO_APP}}:$GITHUB_SHA


    - name: Deploy terraform 
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      run: |
          export TF_VAR_ecr_frontend_app_image="${{vars.ECR_FRONT_REPO_APP}}:$GITHUB_SHA"
          workspace=$(cat .workspace)
          cd infra/
          docker compose run --rm terraform -chdir=deploy init
          docker compose run --rm terraform -chdir=deploy workspace select -or-create $workspace
          docker compose run --rm terraform -chdir=deploy apply -auto-approve
