name: "Deploy to AWS"

on:
  workflow_call


jobs:
  # build the image
  # send the image up to the ecr 

  deploy-envs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4


    - name: Deploy Dev 
      uses: philippsryan/ci-cd-template/.github/workflows/push&apply.yaml
      with:
          environment: "dev"

    - name: Deploy to Production 
      uses: philippsryan/ci-cd-template/.github/workflows/push&apply.yaml
      with:
          environment: "prod"
