name: Integration Tests

on:
  push:
    branches:
    - main

jobs:
  ui:
    uses: ./.github/workflows/ui-verification.yml

  integration:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Start containers
      run: docker compose up -d --build

    - name: Run migrations on database
      run: sleep 15 && docker compose run api ./todoapp migrations

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 21.x
    - name: Setup integration tests
      working-directory: ./api-integration-tests
      run: | 
        npm install
        npx playwright install
    - name: Run Tests
      working-directory: ./api-integration-tests
      run: npx playwright test
      
    - name: Stop containers
      if: always()
      run: docker compose down
